const films = [
    {
        id: 1,
        title: "Titanic",
        year: 1997,
        genre: "Romance/Drama",
        director: "James Cameron",
    },
    {
        id: 2,
        title: "The Shawshank Redemption",
        year: 1994,
        genre: "Drama",
        director: "Frank Darabont",
    },
    {
        id: 3,
        title: "The Godfather",
        year: 1972,
        genre: "Crime/Drama",
        director: "Francis Ford Coppola",
    },
    {
        id: 4,
        title: "The Dark Knight",
        year: 2008,
        genre: "Action/Crime/Drama",
        director: "Christopher Nolan",
    },
    {
        id: 5,
        title: "Forrest Gump",
        year: 1994,
        genre: "Drama/Romance",
        director: "Robert Zemeckis",
    },
    {
        id: 6,
        title: "Inception",
        year: 2010,
        genre: "Action/Adventure/Sci-Fi",
        director: "Christopher Nolan",
    },
    {
        id: 7,
        title: "Pulp Fiction",
        year: 1994,
        genre: "Crime/Drama",
        director: "Quentin Tarantino",
    },
    {
        id: 8,
        title: "The Lord of the Rings: The Return of the King",
        year: 2003,
        genre: "Adventure/Drama/Fantasy",
        director: "Peter Jackson",
    },
    {
        id: 9,
        title: "Schindler's List",
        year: 1993,
        genre: "Biography/Drama/History",
        director: "Steven Spielberg",
    },
    {
        id: 10,
        title: "The Matrix",
        year: 1999,
        genre: "Action/Sci-Fi",
        director: "Lana Wachowski, Lilly Wachowski",
    },
    {
        id: 11,
        title: "The Silence of the Lambs",
        year: 1991,
        genre: "Crime/Drama/Thriller",
        director: "Jonathan Demme",
    },
    {
        id: 12,
        title: "The Departed",
        year: 2006,
        genre: "Crime/Drama/Thriller",
        director: "Martin Scorsese",
    },
    {
        id: 13,
        title: "Gladiator",
        year: 2000,
        genre: "Action/Adventure/Drama",
        director: "Ridley Scott",
    },
    {
        id: 14,
        title: "The Green Mile",
        year: 1999,
        genre: "Crime/Drama/Fantasy",
        director: "Frank Darabont",
    },
    {
        id: 15,
        title: "The Shawshank Redemption",
        year: 1994,
        genre: "Drama",
        director: "Frank Darabont",
    },
    {
        id: 16,
        title: "The Prestige",
        year: 2006,
        genre: "Drama/Mystery/Sci-Fi",
        director: "Christopher Nolan",
    },
    {
        id: 17,
        title: "The Lion King",
        year: 1994,
        genre: "Animation/Adventure/Drama",
        director: "Roger Allers, Rob Minkoff",
    },
    {
        id: 18,
        title: "Fight Club",
        year: 1999,
        genre: "Drama",
        director: "David Fincher",
    },
    {
        id: 19,
        title: "Avatar",
        year: 2009,
        genre: "Action/Adventure/Fantasy",
        director: "James Cameron",
    },
    {
        id: 20,
        title: "Interstellar",
        year: 2014,
        genre: "Adventure/Drama/Sci-Fi",
        director: "Christopher Nolan",
    },
];

export default films;
